baseURL = "https://example.edu"
languageCode = "en-us"
title = "Hendrik Cziommer"
theme = "avicenna"
googleAnalytics = "UA-1234-6"
timeout=1000

[params]
  subtitle= "Diplom Student"
  interests="Machine Learning - Natural Language Processing - Software Engineering "
  kaggle="www.kaggled.de"

[[params.affilation]]
  name = "Technische Universität Dresden"
  position = "Diplom Student"
  contact = "hendrik.cziommer@gmx.de"

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/t0m0ffel"

[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://www.linkedin.com/in/hendrik-cziommer-759ba2130/"

[[params.social]]
  name = "CV"
  icon = "file-text"
  url = "https://linkedin.com/in/hadisinaee/"

# (German Degree, aquivalent to Bachlor + Master Degree)

[[params.introduction.paragraph]]
  text="""I'm a Computer Science student based in Dresden, Germany. In my student job I help to improve the patent application process
  for the <a href="https://www.dpma.de/english/index.html">German Patent and Trade Mark Office</a> using the latest NLP techniques such
  as word embeddings. During my job I worked with fastText and sent2vec to embed patents into a vector space and enable patent examiner
  to determine if ideas are patentable e.g. the idea is not patented already by just transforming the patent application and look at
  a certain amount of similar patents represented as vectors.



   """
[[params.introduction.paragraph]]
  text="""I also researched on a ways to navigate through the vector space through an grafical surface.
  This research project was a collobarion resulting in a <a href="großer_beleg.pdf" target="_blank">paper</a> and
  <a href="großer_beleg_presentation.pdf" target="_blank">presentation</a>.

  """


[[params.projects]]
	[[params.projects.project]]
		name = "Chefbot"
		description  = """Chefbot is a web application generating artificial cooking receipes from a list of freely selectable ingridiences.
		The webapp uses a Vue.js frontend and python based flask backend. The user can select ingridiences and gets a list of matching ingridiences.
		Matching ing are determined by...
		The receipe generation is based on deep neural network created with the FairSeq toolkit<br>
		coloration project with my friend Anja [LINK].
		The web application is PoC

		"""
		project_page = "http://deep.cooking/#/"
		code_link = "https://github.com/t0m0ffel"
		expandable=1

 [[params.projects.project]]
         name = "Cognitive Search in PostgresSQL"
		description  = """The project included research and implementation of word embedding based queries which can be utelized in
		PostgresSQL.
		We used a database containing research papers and a database of movie information.
		We provided a plugin for PostgresSQL which enables the user to perform queries like this: <br>
        <pre><code>Select the 10 most similar movies to the movie ’The Godfather’</code></pre>
        __Result__: ’The Godfather 2’, ’The Godfather 3’, ’Scarface’, ’Good Fellas’...<br><br>
        For the implementation I used Facebooks fastText library for the training of word embeddings. The main task of this project
        was trying different pre-processing stratgies since fastText is designed for texts and not for databases as well as
        finding the best  hyper-parameters. Furthermore, I had use the fastText model in PostgresSQL with a reasonable performance.
        The presentation of results and a working prototype can be found on GitHub"""
		insights="Gained Indepth knowldge of word embeddings techniques"
		code_link = "https://github.com/t0m0ffel/postgres-cognitive-intelligence"
		expandable=1

 [[params.projects.project]]
		name = "Architecture Principles for the Construction of Agile Large Software Systems"
		description="""This project was focused on finding principals which can be used to make software architectures more agile"""
		insights="Gained in depth research expirence with sources"


 [[params.projects.project]]
		name = "Mario Kart"
		description  = """The goal of the project was to simulate a MarioKart race with physical robots. The robots had to recognie virtual
		 items and obstacles as well as real ones via proximity sensors.
		 I mainly focused on the programming of the robots in C as well as building a API for robot controlls in Java.
 		 """
        insights="Improving programming Skills in C and Java as well as learning about converting Signals"
 [[params.projects.project]]
		name = "Sysplace"
		description  = """As virtual reality gains more and more popularity we used C# and the Unity framework to develop
		an application to view a car, rotate it and change certain visual features such as the color.
		My focuse was on getting used to Unity and manipulating the model as well as the intgration of android."""
		insights="Working with 3D Framework and interpersonal skills in an international team"


 [[params.projects.project]]
		name = "Haskell Spellchecker"
		description  = """This project was based on developing a spellchecker with Haskell. To correct words I used a trie data structure and
		the minimal edit distance."""
		insights="Indepth pratice of data structures and algortihmes as well as gaining strong knwoldge in functional programming"


[[params.skills]]
	[[params.skills.skill]]
	    name="Programming"
	    descr="""Since the 8th grade I started programming at school with Delphi 7. At first I thought it was really boring and complicated,
	    but after a few weeks and a short look I started to love it and stick to it with great passion until today."""
	    [[params.skills.skill.subskill]]
	        name="Python, Pandas, NumPy, Jupyter, Numba, flask, django, PyTorch, Keras, Tensorflow"
	        descr="""I startet using Python and Tensorflow since 2016 to train simple deep networks. Over time I gained
	        more and more knwoledge in Python itself as well as the essential frameworks Pandas and Numpy through books
	        and trial and error. PyTorch is my goto framework for impleting neural networks and calcualtions perfomred on
	        GPUs throuh its pythonic philosophy, easy debugability and flexibility. I use flask to deploy models to use them
	        in Webapps.
	        Latley I am intrested in implementing complex algorithms in python using numba to achieve C like performance,
	        as well as speed up existing applications at my work place up to ten fold."""
        [[params.skills.skill.subskill]]
            name="Java, JavaEE, Spring, Hibernate"
            descr="""I first got in touch with Java when I was in school and worked on Android applications. In University
            we learned in deph and I relly enjoyed. It was my goto language for all kinds of programming problems for a long
            time. During my internship in India I impletet a Webapplication to automate the internal release process using
            Spring, OracleDB, Hibernate and AngularJS."""
        [[params.skills.skill.subskill]]
            name="Haskell"
            descr="""I learned about Haskell and functional programming in general at university. The lecture also included
            tranlating Haskell Code to C and Assembler Code. Haskell offers a style to implement algorithms in a very short,
            mathematical but - when you get used to it - easy to unterstand way. I really appricate the approaches of
            Java and JavaScript to implement this style to make programms easier to understand."""
        [[params.skills.skill.subskill]]
            name="JavaScript/HTML5/CSS3, Vue.js, Angular.js, Vega.js"
            descr="""During my internships I have used JavaScript in myriad projects using different frameworks such as Angular.js and
            Vue.js.
            I used Vega.js which is build on D3 to visulaize word embeddings and build an interactive plot to navigate
            through the word space."""
        [[params.skills.skill.subskill]]
            name="C/C++"
            descr="""As fast low-level languages C and C++ are used in a wide varity of fields ranging from robots to
            machine learning algorithms. In my first semester at university I build a very basic agent playing Nine men's morris.
            Later I used C to controll robots with Arduino and now I work with starspace and fastText to enhance the quality of
            word embeddings"""
        [[params.skills.skill.subskill]]
            name="PostgresSQL, OracleDB, MySQL"
            descr="""Databases are 	ubiquitous  in applications of all kinds. During my work experience I used PostgresSQL
            to enhance queries by including word embeddings. I also used OracleDB and MySQL to persit data in various
            webapplications
            """